version: "3.3"
services:
  landing-service:
    build: ./landing
    hostname: landing-service
    ports:
      - "5050:5050"
    networks:
      - my-network
    depends_on:
      - add-service
      - minus-service
      - multiply-service
      - divide-service
      - lcm-service
      - hcf-service
      - modulus-service

  add-service:
    build: ./add
    hostname: add-service
    ports:
      - "5001:5050"
    networks:
      - my-network

  minus-service:
    build: ./minus
    ports:
      - "5002:5050"
    networks:
      - my-network

  multiply-service:
    build: ./multiply
    ports:
      - "5003:5050"
    networks:
      - my-network

  divide-service:
    build: ./divide
    ports:
      - "5004:5050"
    networks:
      - my-network

  lcm-service:
    build: ./lcm
    ports:
      - "5005:5050"
    networks:
      - my-network

  hcf-service:
    build: ./hcf
    ports:
      - "5006:5050"
    networks:
      - my-network

  modulus-service:
    build: ./modulus
    ports:
      - "5007:5050"
    networks:
      - my-network

networks:
  my-network:
